[package]
name = "saysthbot-reborn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version ="3.2.6", features = ["derive", "env"]}
rbatis = "3.1.11"
telegram-bot = "0.8.0"
wd_log = "0.1.5"
tokio = { version = "^0.2", features = ["full"]}
futures = "^0.3"